# Generated by Django 4.0.3 on 2022-04-10 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='fisrtName',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='username',
            new_name='userName',
        ),
    ]
